In [1]:
#import das libs
import pandas as pd

In [2]:
#importando arquivos do drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
#declarando diret√≥rio principal
ROOT_DATA_PATH = "drive/MyDrive/data/"

In [4]:
#lendo arquivo movies.csv informando o separador
m_df = pd.read_csv(f'{ROOT_DATA_PATH}/movies.csv', sep=';')
#limpando linhas com valor invalido se existir
m_df.dropna()
m_df.head()

   1               (Dinosaur Planet, 2003)
0  2    (Isle of Man TT 2004 Review, 2004)
1  3                     (Character, 1997)
2  4  (Paula Abdul's Get Up & Dance, 1994)
3  5      (The Rise and Fall of ECW, 2004)
4  6                          (Sick, 1997)

In [5]:
#setando os nomes das colnas
nomes_colunas = ['Movie_Id', 'Title_Year']
m_df.columns = nomes_colunas
m_df

      Movie_Id                                         Title_Year
0            2                 (Isle of Man TT 2004 Review, 2004)
1            3                                  (Character, 1997)
2            4               (Paula Abdul's Get Up & Dance, 1994)
3            5                   (The Rise and Fall of ECW, 2004)
4            6                                       (Sick, 1997)
...        ...                                                ...
4493      4495  (Clifford: Happy Birthday Clifford / Puppy Lov...
4494      4496                      (Farewell My Concubine, 1993)
4495      4497                                 (Texasville, 1990)
4496      4498                                      (Gonin, 2000)
4497      4499                                 (In My Skin, 2002)

[4498 rows x 2 columns]

In [29]:
#lendo o arqivo customers_rating.csv informando q tem cabecalho e o separador
cr_df = pd.read_csv(f'{ROOT_DATA_PATH}/customers_rating.csv',header=0, sep=';')
#limpando linhas com valor invalido se existir
cr_df.dropna()
cr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24053764 entries, 0 to 24053763
Data columns (total 4 columns):
 #   Column    Dtype
---  ------    -----
 0   Cust_Id   int64
 1   Rating    float64
 2   Date      object
 3   Movie_Id  int64
dtypes: float64(1), int64(2), object(1)
memory usage: 734.1+ MB

##Entreg√°veis

1. Jupyter Notebook ou arquivo Python que responda as seguintes perguntas:

In [7]:
# 1.1. Quantos filmes est√£o dispon√≠veis no dataset?

#pegando qtds dos IDs dos filmes de forma unica
qtd_filmes = m_df['Movie_Id'].nunique()
print(f"O n√∫mero de filmes dispon√≠veis no dataset √© {qtd_filmes}.")

O n√∫mero de filmes dispon√≠veis no dataset √© 4498.

In [8]:
#1.2. Qual √© o nome dos 5 filmes com melhor m√©dia de avalia√ß√£o?

# Mesclando os dataframes
merged_df = pd.merge(cr_df, m_df, on='Movie_Id')

# Calculando a m√©dia de avalia√ß√£o para cada filme
mean_ratings = merged_df.groupby(['Title_Year'])['Rating'].mean()

# Ordenando os filmes com base na m√©dia de avalia√ß√µes
sorted_ratings = mean_ratings.sort_values(ascending=False)

# Obtendo os 5 primeiros filmes com a melhor m√©dia de avalia√ß√£o
top_5_movies = sorted_ratings.head(5)

print("Os 5 filmes com a melhor m√©dia de avalia√ß√£o s√£o:")
print(top_5_movies)

Os 5 filmes com a melhor m√©dia de avalia√ß√£o s√£o:
Title_Year
(Lost: Season 1, 2004)                                                                 4.670989
(Ghost in the Shell: Stand Alone Complex: 2nd Gig, 2005)                               4.586364
(The Simpsons: Season 6, 1994)                                                         4.581296
(Inu-Yasha, 2000)                                                                      4.554434
(Lord of the Rings: The Return of the King: Extended Edition: Bonus Material, 2003)    4.552000
Name: Rating, dtype: float64

In [9]:
#1.3. Quais os 9 anos com menos lan√ßamentos de filmes?

# Extraindo o ano de lan√ßamento a partir da coluna 't√≠tulo e ano de lan√ßamento'
m_df['Year'] = m_df['Title_Year'].str[-5:-1]

# Contando o n√∫mero de lan√ßamentos por ano
count_per_year = m_df['Year'].value_counts()

# Ordenando os anos com base no n√∫mero de lan√ßamentos
sorted_years = count_per_year.sort_values()

# Obtendo os 9 anos com menos lan√ßamentos de filmes
bottom_9_years = sorted_years.head(9)

print("Os 9 anos com menos lan√ßamentos de filmes s√£o:")
print(bottom_9_years)

Os 9 anos com menos lan√ßamentos de filmes s√£o:
1917    1
1922    1
1926    1
1915    1
1924    2
1916    2
1931    2
1918    2
1929    2
Name: Year, dtype: int64

In [24]:
#1.4. Quantos filmes que possuem avalia√ß√£o maior ou igual a 4.7, considerando apenas os filmes avaliados na √∫ltima data de avalia√ß√£o do dataset?

# Convertendo a coluna 'Date' para o formato de data
cr_df['Data'] = pd.to_datetime(cr_df['Date'])

# Encontrando a √∫ltima data de avalia√ß√£o
ultima_data = cr_df['Data'].max()

# Filtrando os filmes avaliados na √∫ltima data de avalia√ß√£o
filmes_ultima_data = cr_df[cr_df['Data'] == ultima_data]

# Contando o n√∫mero de filmes com uma avalia√ß√£o maior ou igual a 4.7
filmes_com_alta_avaliacao = filmes_ultima_data[filmes_ultima_data['Rating'] >= 4.7]['Movie_Id'].unique()

#tamanho da serie com os ids dos filmes
num_filmes_com_alta_avaliacao = len(filmes_com_alta_avaliacao)

print(f"O n√∫mero de filmes que possuem avalia√ß√£o maior ou igual a 4.7 na √∫ltima data de avalia√ß√£o do dataset √© {num_filmes_com_alta_avaliacao}.")

O n√∫mero de filmes que possuem avalia√ß√£o maior ou igual a 4.7 na √∫ltima data de avalia√ß√£o do dataset √© 780.

In [39]:
#1.5. Dos filmes encontrados na quest√£o anterior, quais s√£o os 10 filmes com as piores notas e quais as notas?

# Obtendo os filmes da quest√£o anterior
filmes_com_alta_avaliacao

# Filtrando os filmes com IDs da lista 'filmes_com_alta_avaliacao'
filmes_filtrados = cr_df[(cr_df['Movie_Id'].isin(filmes_com_alta_avaliacao))]

# Ordenando os filmes filtrados com base no rating em ordem ascendente
filmes_piores_ratings = filmes_filtrados.sort_values('Rating').groupby('Movie_Id').head(1).head(10)

# Juntando os dados do t√≠tulo e ano de lan√ßamento dos filmes
piores_filmes = pd.merge(filmes_piores_ratings, m_df, on='Movie_Id')[['Title_Year', 'Rating']]

print("Os 10 filmes com as piores notas s√£o:")
print(piores_filmes)

Os 10 filmes com as piores notas s√£o:
                                   Title_Year  Rating
0                           (Happiness, 1998)     1.0
1                   (Death Becomes Her, 1992)     1.0
2  (The Life Aquatic with Steve Zissou, 2004)     1.0
3           (Evil Dead 2: Dead by Dawn, 1987)     1.0
4                    (Along Came Polly, 2004)     1.0
5       (Monarch of the Glen: Series 2, 2001)     1.0
6                         (Patch Adams, 1998)     1.0
7                   (Road to Perdition, 2002)     1.0
8                       (About Schmidt, 2002)     1.0
9                     (Men in Black II, 2002)     1.0

In [40]:
#1.6. Quais os id's dos 5 customers que mais avaliaram filmes e quantas avalia√ß√µes cada um fez?

# Obtendo os 5 clientes que mais avaliaram filmes
top_5_customers = cr_df['Cust_Id'].value_counts().head(5)

print("Os 5 clientes que mais avaliaram filmes e suas respectivas contagens de avalia√ß√µes s√£o:")
print(top_5_customers)

Os 5 clientes que mais avaliaram filmes e suas respectivas contagens de avalia√ß√µes s√£o:
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
Name: Cust_Id, dtype: int64